version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
      - NEXT_PUBLIC_LIVEBLOCKS_PUBLIC_KEY_PRODUCTION=${NEXT_PUBLIC_LIVEBLOCKS_PUBLIC_KEY_PRODUCTION}
    restart: always
    volumes:
      - ./public:/app/public
